spring:
  application:
    name: AUTHORIZATION
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pension-management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: ${DB_USERNAME:suki}
    password: ${DB_PASSWORD:password}
    embedded-database-connection: h2
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:8002}

management:
  endpoints:
    web:
      exposure:
        include: "*"

authorization:
  jwt:
    secret-key: ${SECRET_KEY:secret}
  auth-whitelist:
    - "/authorization/login"
    - "/authorization/pensioner"

